version: '2'
services:
  app:
    image: yiisoftware/yii2-php:7.2-apache
    ports:
      - '80:80'
    volumes:
      - ./:/app
    container_name: app
    links: 
      - 'db'
  db:
    image: mysql
    ports:
      - '3306:3306'
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --default-authentication-plugin=mysql_native_password
